services:
  - type: web
    name: clifton-traders
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production