services:
  - type: web
    name: clifton-traders
    env: node
    plan: free
    buildCommand: npm install && vite build && esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --external:bufferutil --external:utf-8-validate
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production